# Generated by Django 3.2.8 on 2021-11-30 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211114_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
